### ISSUE TITLE
스타일링 충돌문제

### ISSUE THREAD

**Issue by hwisaac** [React-Team-Project/Youtube-Clone#31]
## 문제
![image](https://user-images.githubusercontent.com/54179672/213434628-8659d9f6-a01a-4ba5-ab08-331cfec31551.png)

 > 반응형 디자인 구현 중 박스 높이 조절이 안되는 문제 발생
1. 높이를 안줘도 높이값을 가지고 있음 
2. `height: auto` 로 자식요소에 기반한 높이 조절 입력이 안됨

<img width="393" alt="image" src="https://user-images.githubusercontent.com/54179672/213434721-32a8158c-7562-4dd6-a05d-01a1b3f41455.png">

![image](https://user-images.githubusercontent.com/54179672/213434910-6ee29738-9a6b-43ad-a944-11d86416772e.png)
 
## 문제원인
> index.css 에서 `#root` 에 grid 템플릿으로 설정한 코드가 전역적으로 적용되어 각 컴포넌트 div 박스에도 적용되는 것으로 확인
```css
#root {
  display: grid;
  grid-template-columns: auto 1fr;
  grid-template-rows: 55px auto;
  grid-template-areas:
  "nav nav"
  "aside main";
}
```

## 해결 
- root 에 적용된 스타일링 제거하면 정상적으로 스타일링 가능
- 스타일링 옵션은 개개의 컴포넌트별로 따로 설정하고, 전역적인 설정은 웬만하면 자제해주세요
